; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nicenano]
platform = nordicnrf52
board = nicenano
framework = arduino
upload_protocol = nrfutil
lib_archive = no  ; Crucial for TinyUSB interrupt vectors
build_flags = 
    -DUSE_TINYUSB
;lib_deps =  https://github.com/adafruit/Adafruit_nRF52_Arduino //To add Ble support and other features, if something doesnt work try add this lib.

lib_deps =
    adafruit/Adafruit TinyUSB Library
    adafruit/Adafruit GFX Library
    adafruit/Adafruit Sharp Memory Display